#187419055 Added tests for user-login
atlp-rwanda/hackers-ec-be pull request #14
Opened 2024-04-20 21:18 UTC by cyusasnave

**What does this pull request do?**

This pull request holds login tests and also the route for the root of the project

**Endpoints:**

`/ `: root of the project

**How to test this?**

- Clone the repo and cd into it
- run `npm install`
- Enter the `.env` based on `.env.example`
- the run `npm run test `and for the score run `npm run test:ci`

**Story Id**

#187419055

2024-04-21 11:31 UTC, leandreAlly requested changes

2024-04-21 11:31 UTC, leandreAlly commented on .github/workflows/node.js.yml
> +      - feat-user-login-187419055
We can't always add branch here, this must be global to avoid touching a lot of files.

2024-04-21 11:31 UTC, leandreAlly commented on src/__test__/users.test.ts
>      // Your test implementation goes here
why you left empty test cases, if you're not using them, please remove it.

2024-04-21 11:31 UTC, leandreAlly commented on src/__test__/users.test.ts
> +
for now your test has coverage of 79% we need at least 85%

2024-04-22 08:13 UTC, Tuyisenge2 approved these changes

2024-04-22 14:32 UTC, Hakizimana-Clement approved these changes

2024-04-22 15:57 UTC, Hakizimana-Clement approved these changes

2024-04-22 18:14 UTC, merged