feat(Reset-password):User who forgot password can reset it via email
atlp-rwanda/hackers-ec-be pull request #17
Opened 2024-04-23 22:12 UTC by YvetteNyibuka

#### What does this PR do?
          Enables users who forgot his/her password to reset it and get a new one without creating a new account
#### Description of Task to be completed?

1. A user who forgot their password can request resetting it
2. Sending a reset password email containing a link along with a token to reset the password
3. Reset the password using the provided token
4. Token is used only once even if it is not expired

#### How should this be manually tested?

1. Chrone Repository into your local machine
2. Run `npm install`
3. Fill all environment variables in `.env` file as they appear in .env example file
4. Run `npm run dev`
5. Use Postman to create a user on the endpoint: `api/v1/users/register`
6. Create another request in Postman to request a password reset on the endpoint: `/api/v1/users/forgot-password`
7. Check the message containing the reset link on the email you have provided or the one of the account you are resetting the password for
8.  Add another request for resetting the password by setting the token you have got from the above step in the params on the endpoint: `/api/v1/users/reset-password/:token` and provide a new password in the body
9. Try login with both old and new passwords to see if the reset happened successfully on the endpoint: `/api/v1/users/login`

#### What are the relevant pivotal tracker/Trello stories?

#187419058

2024-04-26 12:01 UTC, GarrixA approved these changes

2024-04-26 12:16 UTC, leandreAlly requested changes

2024-04-26 12:16 UTC, leandreAlly commented on src/controllers/usedTokens.json
> +	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5NWNiNjhkLTZhZDMtNDcxMS1hMzVjLWFmYTQwYzI3YmRkYSIsImVtYWlsIjoiaXphbnlpYnVrYXl2ZXR0ZTEwNUBnbWFpbC5jb20iLCJpYXQiOjE3MTQwMDAyODIsImV4cCI6MTcxNDA4NjY4Mn0.
@YvetteNyibuka why do we still this token object in out app? please remove them.

2024-04-26 12:28 UTC, Hakizimana-Clement approved these changes

2024-04-26 13:22 UTC, YvetteNyibuka commented on src/controllers/usedTokens.json
> +	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5NWNiNjhkLTZhZDMtNDcxMS1hMzVjLWFmYTQwYzI3YmRkYSIsImVtYWlsIjoiaXphbnlpYnVrYXl2ZXR0ZTEwNUBnbWFpbC5jb20iLCJpYXQiOjE3MTQwMDAyODIsImV4cCI6MTcxNDA4NjY4Mn0.
It only contains unused tokens if the token is used or expired it is removed. That's how I store them.

2024-04-29 20:27 UTC, leandreAlly approved these changes

2024-04-29 20:27 UTC, merged