#187419054 fix user authentication
atlp-rwanda/hackers-ec-be pull request #25
Opened 2024-04-29 09:17 UTC by GarrixA

**Logout functionality**

_Description_

User will be able to exit the application for some reasons
Endpoint
- Post /api/v1/users/logout

How to test this:

Clone the repo
- Run npm install to install the dependances
- Add your environment variable as it is listed in .env.examples
- Run npm run dev to start the server
- Navigate to postman or anywhere you normally tests your endpoints
- By /api/v1/users/register endpoint you will be able to signup a user
- By /api/users/login endpoint you will be able to login your user
- And finally by /api/v1/users/logout endpoint you will be able to log out loggedin user
- grab token from login and pass it in Authorization, use Bearer token

  Pivotal tracker ID:
        #187419054

2024-04-29 14:10 UTC, leandreAlly requested changes

2024-04-29 14:10 UTC, leandreAlly commented on src/controllers/logoutController.ts
> +			const blacklistedToken = await Blacklist.findOne({ where: { token } });
we don't need specific controller to the logout we can have this function into userController.ts

2024-04-29 14:10 UTC, leandreAlly commented on src/controllers/logoutController.ts
> +		if (token) {
since we're we have the middleware which checks if user is logged in we don't need this condition we can directly access token from header and log user out

2024-04-29 14:10 UTC, leandreAlly commented on src/controllers/logoutController.ts
> +				return res
as in the model you said the id will be generated by default we don't need this manual generating in this functions you can only pass token .
Blacklist.create({ token }); and don't forget to make id optional in model interface so we avoid typescript error.


export interface BlacklistModelAtributes {
	id?: string;
	token: string;
}

2024-04-29 14:10 UTC, leandreAlly commented on src/controllers/logoutController.ts
>  		return res
remove this code  down below they're useless.

		return res
			.status(401)
			.json(new HttpException("UNAUTHORIZED", "Already logged out"));

2024-04-30 00:21 UTC, Angemichel12 approved these changes

2024-04-30 00:22 UTC, YvetteNyibuka approved these changes
Good Job Aphrodis!

2024-04-30 00:23 UTC, leandreAlly approved these changes

2024-04-30 00:25 UTC, merged