187431151-develop user sign up end points
atlp-rwanda/hackers-ec-be pull request #4
Opened 2024-04-16 14:13 UTC by Tuyisenge2

### What does this PR do?
user will signup with email and password
#### Description of Task to be completed?
have following  endpoint 
/api/v1/register
#### How should this be manually tested?
first install all packages by "npm install"
then create your own .env and fill all reqiured environment variables
after create database
#### What are the relevant pivotal tracker/Trello stories?
187431151

2024-04-16 14:42 UTC, cyusasnave requested changes

2024-04-16 14:42 UTC, cyusasnave commented on src/controllers/userController.ts
> +
Hello, Tito. We need a new user model. That one michel used, it was only for testing purposes. 
For registering a user, we should have the following in our model:
1. id (Unique)
2. googleId (Unique)
3. First name
4. Last name
5. Username (Unique)
6. Email (Unique)
7. Password
8. Confirm Password
9. Address(Optional): for shipping purposes
10. Phone number
11. Gender(Optional)
12. Date of birth(Optional)
13.  Profile picture (Optional)
14. IsVerified(default to false)
15. role ( Can only choose between " Guest, buyer and seller(Vendor)")

Any other field required will be added.

2024-04-16 15:47 UTC, leandreAlly commented on src/controllers/userController.ts
> +
@cyusasnave we need to see @Tuyisenge2 come with his own model not telling him what do, if he have any blocker he can always drop query on slack channel

2024-04-18 22:24 UTC, Hakizimana-Clement approved these changes

2024-04-19 10:43 UTC, leandreAlly approved these changes

2024-04-19 10:43 UTC, merged