#[187419046] Setup API documentation
atlp-rwanda/hackers-ec-be pull request #5
Opened 2024-04-16 17:05 UTC by kwizera-bonheur25

#### What does this PR do?

- add the chore of setup API documentation
 
#### Description of Task to be completed?

- The setup the swagger documentation using swagger

#### How should this be manually tested?

-clone the project
- run npm run dev
- open the web browser add the http://localhost:PORT/api/v1/Docs/ this port will replaced by your running server port

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#187419046

#### Screenshots of the running swagger documentation interface

<img"1440" alt="Screenshot 2024-04-16 at 18 52 58" src="https://github.com/atlp-rwanda/hackers-ec-be/assets/166609330/3ad7c2bd-275e-4931-9fc7-ddb28e872124"> width="1440" alt="Screenshot 2024-04-16 at 18 52 58" src="https://github.com/atlp-rwanda/hackers-ec-be/assets/166609330/3ad7c2bd-275e-4931-9fc7-ddb28e872124">

2024-04-17 07:53 UTC, Angemichel12 approved these changes

2024-04-17 07:58 UTC, cyusasnave requested changes

2024-04-17 07:58 UTC, cyusasnave commented on src/app.ts
> +  app.use("/api/v1/Docs",swaggerUi.serve,swaggerUi.setup(swaggerSpec))
Wrong end-point naming convention
Correct this

2024-04-17 07:59 UTC, YvetteNyibuka approved these changes

2024-04-17 08:23 UTC, cyusasnave approved these changes

2024-04-18 07:17 UTC, leandreAlly approved these changes

2024-04-18 07:18 UTC, merged