#187419065 Fixing productStatus type from string to boolean
atlp-rwanda/hackers-ec-be pull request #59
Opened 2024-05-26 20:42 UTC by YvetteNyibuka

#### What does this PR do?
Changing product availability status  type from string to boolean

#### Description of Task to be completed?
- Changing product availability status  type from string to boolean
- Making update status an on/off button

#### How should this be manually tested?

Try to access all/single products as buyer and seller and see the results, buyer see only available products

#### What are the relevant pivotal tracker/Trello stories?

#187419065

2024-05-28 14:33 UTC, GarrixA approved these changes

2024-05-28 14:34 UTC, cyusasnave approved these changes

2024-05-28 15:58 UTC, leandreAlly requested changes

2024-05-28 15:58 UTC, leandreAlly commented on src/middlewares/product.middlewares.ts
> +	if (product?.dataValues.isAvailable === false) {
remove false accession and use  (!) operator 
if  (!product?.dataValues.isAvailable ) {
}

2024-05-28 15:58 UTC, leandreAlly commented on src/middlewares/product.middlewares.ts
>  					expiryDate: {
just use (isAvailable) and remove true.

2024-05-28 15:58 UTC, leandreAlly commented on src/mock/static.ts
> +	isAvailable: true,
just use (isAvailable) and remove true.

2024-05-28 15:58 UTC, leandreAlly commented on src/mock/static.ts
> +	isAvailable: true,
just use (isAvailable) and remove true.

2024-05-28 15:58 UTC, leandreAlly commented on src/utils/products.expiration.ts
> +			product.isAvailable === true
remove this "product.isAvailable === true" and have only 
"product.quantity > 0 &&
			product.isAvailable"

2024-05-28 15:58 UTC, leandreAlly commented on src/utils/products.expiration.ts
> +			const isAvailable = false;
delete this line  const isAvailable = false;

2024-05-28 15:58 UTC, leandreAlly commented on src/utils/products.expiration.ts
> +				{ isAvailable },
replace this with "{ isAvailable }," with "{ !isAvailable }", after deleting the above container variable

2024-05-28 15:58 UTC, leandreAlly commented on src/utils/socket.util.ts
> +	});
optional improvement: await isLogin(socketInstance) ? next() : socketInstance.disconnect(true);

2024-05-28 15:58 UTC, leandreAlly commented on public/login.html
> +				fetch("http://localhost:5500/api/v1/users/login", {
put this back this to deployed version!

2024-05-28 15:58 UTC, leandreAlly commented on public/login.html
> +							window.location.href = "http://localhost:5500/api/v1/chats";
same here

2024-05-28 15:58 UTC, leandreAlly commented on src/__test__/cart.test.ts
> +			{ isAvailable: true },
also change this

2024-05-28 15:58 UTC, leandreAlly commented on src/__test__/order.test.ts
> +			{ isAvailable: true },
and here also

2024-05-28 15:58 UTC, leandreAlly commented on src/__test__/order.test.ts
> +			{ isAvailable: true, price: 5 },
and here also change from "{ isAvailable: true,}" to ""{ isAvailable},

2024-05-28 15:58 UTC, leandreAlly commented on src/__test__/order.test.ts
> +			{ isAvailable: true, price: 499000 },
and here also change from "{ isAvailable: true,}" to ""{ isAvailable},

2024-05-28 15:58 UTC, leandreAlly commented on src/__test__/review.test.ts
> +			{ isAvailable: true },
and here also change from "{ isAvailable: true,}" to ""{ isAvailable},

2024-05-28 15:58 UTC, leandreAlly commented on src/__test__/sales.test.ts
> +			{ isAvailable: true, price: 5 },
and here also change from "{ isAvailable: true,}" to ""{ isAvailable},

2024-05-28 15:58 UTC, leandreAlly commented on src/__test__/sales.test.ts
> +			{ isAvailable: true, price: 499000 },
and here also change from "{ isAvailable: true,}" to ""{ isAvailable},

2024-05-28 15:58 UTC, leandreAlly commented on src/controllers/productController.ts
> +			where: { id: product_id, isAvailable: true },
and here also change from "{ isAvailable: true,}" to ""{ isAvailable},

2024-05-29 10:39 UTC, Hakizimana-Clement approved these changes

2024-05-29 10:39 UTC, Hakizimana-Clement approved these changes

2024-05-29 10:39 UTC, Hakizimana-Clement approved these changes

2024-05-29 10:42 UTC, Hakizimana-Clement approved these changes

2024-05-29 12:33 UTC, leandreAlly approved these changes

2024-05-29 12:34 UTC, merged