fix(products): fix of delete in relationships
atlp-rwanda/hackers-ec-be pull request #72
Opened 2024-07-05 09:39 UTC by GarrixA

# This fix is here to
- Handle error of products in relations when tried to be deleted

## how to test this
- clone the repo
- navigate to my branch
- Login a seller
- Delete a product that has been ordered

2024-07-08 14:05 UTC, cyusasnave requested changes

2024-07-08 14:05 UTC, cyusasnave commented on src/database/seeders/20240428145740-demo-user.js
> +// /** @type {import('sequelize-cli').Migration} */
Since this lines are commented, i don't think you need them. You can remove them. Apart from that everything is great

2024-07-08 14:51 UTC, cyusasnave approved these changes

2024-07-09 09:53 UTC, kwizera-bonheur25 approved these changes

2024-07-09 15:45 UTC, leandreAlly approved these changes

2024-07-09 15:46 UTC, merged